name: soul
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # Fixed SDK constraint syntax

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.2.1
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Updated to a more stable version

flutter:
  uses-material-design: true

  assets:
    - assets/.env
